import{a as b,S as w,i as l}from"./assets/vendor-CauDeeDU.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();async function L(e,r){const a=`https://pixabay.com/api/?${new URLSearchParams({key:"51145498-f51992c20e23a6f6f425bd97f",q:e,image_type:"photo",orientation:"horizontal",max_width:320,max_height:200,safesearch:"true",per_page:15,page:r})}`;try{const t=await b.get(a);return{hits:t.data.hits,totalHits:t.data.totalHits}}catch(t){return console.error("Ошибка",t),[]}}const v=new w(".gallery a",{caption:!0,captionDelay:250}),S=document.querySelector(".gallery");function p(e){let r="";e==null||e.forEach(o=>{r+=`<li> 
      <a href= "${o.largeImageURL}" class="large-img">
       <img src="${o.webformatURL}" class="small-img" alt="${o.tags}">
       </a>
       <div class="under-image-info">
       <p> <span> Likes </span> <br> ${o.likes} </p>
       <p> <span> Views </span> <br> ${o.views} </p>
       <p> <span> Comments </span> <br> ${o.comments} </p>
       <p> <span> Downloads </span> <br> ${o.downloads} </p>
       </div>

    </li> `}),S.insertAdjacentHTML("beforeend",r),v.refresh()}function O(){const e=document.querySelector(".gallery");e&&(e.innerHTML="")}function q(){const e=document.querySelector(".loader");e&&(e.style.display="block")}function I(){const e=document.querySelector(".loader");e&&(e.style.display="none")}const g=document.querySelector(".js-load-more-btn"),P=()=>g.style.display="block",m=()=>g.style.display="none",d=document.querySelector(".form");let c="",y="",n=1;const i={position:"topRight",timeout:4e3,close:!0,progressBar:!0,icon:"fas fa-check",closeOnClick:!1,pauseOnHover:!0};d.addEventListener("submit",async function(e){if(e.preventDefault(),m(),d.elements["search-text"].value.trim()===""){l.warning({message:"Input value can't be empty!",color:"red",...i});return}c=d.elements["search-text"].value.trim(),y=c,n=1,O();const o=(await h(n)).hits;p(o),o.length<15&&l.warning({message:"We are sorry, but you've reached the end of search results",color:"red",...i}),o.length>=15&&P()});let f=!1;async function h(e){if(f)return[];f=!0,q();try{const r=await L(c,e);return r.hits.length===0?(l.warning({message:"Sorry, there are no images matching <br> your search query. Please try again!",color:"red",...i}),[]):r}catch(r){return l.error({message:`Oops, something went wrong! ${r}`,color:"red",...i}),[]}finally{I(),f=!1}}const $=document.querySelector(".js-load-more-btn");$.addEventListener("click",async function(){if(y===c){n++;const e=await h(n),r=e.totalHits,o=Math.ceil(r/15);(n>=o||r<15)&&(m(),l.warning({message:"We are sorry, but you've reached the end of search results",color:"red",...i}));const a=e.hits;(a==null?void 0:a.length)>0?(p(a),x()):m()}});function x(){const o=document.querySelector("li").getBoundingClientRect().height*2;window.scrollBy({top:o,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
