import{S as b,a as w,i as n}from"./assets/vendor-CauDeeDU.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&a(u)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const L=new b(".gallery a",{caption:!0,captionDelay:250}),v=document.querySelector(".gallery");function p(t){let o="";t==null||t.forEach(e=>{o+=`<li> 
      <a href= "${e.largeImageURL}" class="large-img">
       <img src="${e.webformatURL}" class="small-img" alt="${e.tags}">
       </a>
       <div class="under-image-info">
       <p> <span> Likes </span> <br> ${e.likes} </p>
       <p> <span> Views </span> <br> ${e.views} </p>
       <p> <span> Comments </span> <br> ${e.comments} </p>
       <p> <span> Downloads </span> <br> ${e.downloads} </p>
       </div>

    </li> `}),v.insertAdjacentHTML("beforeend",o),L.refresh()}function S(){const t=document.querySelector(".gallery");t&&(t.innerHTML="")}function O(){const t=document.querySelector(".loader");t&&(t.style.display="block")}function q(){const t=document.querySelector(".loader");t&&(t.style.display="none")}const g=document.querySelector(".js-load-more-btn"),I=()=>g.style.display="block",m=()=>g.style.display="none";async function P(t,o){const a=`https://pixabay.com/api/?${new URLSearchParams({key:"51145498-f51992c20e23a6f6f425bd97f",q:t,image_type:"photo",orientation:"horizontal",max_width:320,max_height:200,safesearch:"true",per_page:15,page:o})}`;try{const r=await w.get(a);return{hits:r.data.hits,totalHits:r.data.totalHits}}catch(r){return console.error("Ошибка",r),[]}}const d=document.querySelector(".form");let c="",y="",i=1;const l={position:"topRight",timeout:4e3,close:!0,progressBar:!0,icon:"fas fa-check",closeOnClick:!1,pauseOnHover:!0};d.addEventListener("submit",async function(t){if(t.preventDefault(),m(),d.elements["search-text"].value.trim()===""){n.warning({message:"Input value can't be empty!",color:"red",...l});return}c=d.elements["search-text"].value.trim(),y=c,i=1,S();const e=(await h(i)).hits;if(!e||!Array.isArray(e)||e.length===0){n.warning({message:"Sorry, there are no images matching <br> your search query. Please try again!",color:"red",...l});return}p(e),e.length>=15&&I(),e&&e.length<15&&n.warning({message:"We are sorry, but you've reached the end of search results",color:"red",...l})});let f=!1;async function h(t){if(f)return{hits:[]};f=!0,O();try{const o=await P(c,t),e=o.hits;return!e||!Array.isArray(e)||e.length===0?{hits:[]}:o}catch(o){return n.error({message:`Oops, something went wrong! ${o}`,color:"red",...l}),{hits:[]}}finally{q(),f=!1}}const $=document.querySelector(".js-load-more-btn");$.addEventListener("click",async function(){if(y===c){i++;const t=await h(i),o=t.totalHits||0,e=Math.ceil(o/15);(i>=e||o<15)&&(m(),n.warning({message:"We are sorry, but you've reached the end of search results",color:"red",...l}));const a=t.hits||[];(a==null?void 0:a.length)>0?(p(a),x()):m()}});function x(){const e=document.querySelector("li").getBoundingClientRect().height*2;window.scrollBy({top:e,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
